### ISSUE TITLE
PHP RQL parser and data structure

### ISSUE THREAD

**Issue by ghost** [persvr/rql#43]
Hi!
I intend to use your query language for a PHP REST API. I intend to use DDD with CQRS under the hud, so the GET requests will be converted into Query subclass instances (for example GetUserByIdQuery), and those instances will be processed by the query domain logic. These Query subclass instances should contain the resource id, possibly some additional data (for example user identity) and possibly the RQL conditions transformed to an easy traversable data structure. So by sending such a Query to a storage adapter, it can easily convert it to SQL, noSQL, or whatever queries it uses. Do you have some recommendations about the parser and the data structure?

**Comment by amrlafi** [comment]
Hi,
I'm trying to develop .NET parser. Does this project, or php-rql-parser used a parser generator tool such as ANTLR or similar?

**Comment by wshager** [comment]
@amrlafi No, it doesn't. AFAIK it's overkill to use a formal grammar, since RQL is really just parentheses-only. You're welcome to write one of course, but you could also take a look at the regular expressions in the code or write a simple recursive descent parser.
