### ISSUE TITLE
Case in-sensitive search

### ISSUE THREAD

**Issue by mavalur** [persvr/rql#67]
Is there an API syntax to include to support case in-sensitive search? 
Say for example eq(vehicleType,'car') should match "Car", "CAR" , "car"

**Comment by wshager** [comment]
@mavalur AFAIK eq(a,b) tests for strict equality, so that won't be an option. You yourself could implement regular expression matches(a,b,flags) or the SQL flavor like() as mentioned in http://doc.apsstandard.org/2.1/spec/rql/.

**Comment by mavalur** [comment]
Got it. Thank you.
